In [3]:
import numpy as np

# carregando os dados com numpy

entradas = np.genfromtxt('/home/excript/machine_learning/teste_python/iris.data',delimiter=',',usecols=(0,1,2,3))
saidas = np.genfromtxt('/home/excript/machine_learning/teste_python/iris.data',delimiter=',',usecols=(4))

print(len(entradas))
print(len(saidas))

150
150


In [5]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

# mostrando as 5 primeiras amostras que sao Iris-setosas
print(entradas[:5],saidas[:5])
# mostrando as 5 ultimas amostras que sao Iris-virginica
print(entradas[-5:],saidas[-5:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] [0. 0. 0. 0. 0.]
[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]] [2. 2. 2. 2. 2.]


In [8]:
# 105 amostras pra treino, 35 de cada classe

entradas_treino = np.concatenate((entradas[:35],entradas[50:85],entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35],saidas[50:85],saidas[100:135]))

print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [9]:
entradas_teste = np.concatenate((entradas[35:50],entradas[85:100],entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50],saidas[85:100],saidas[135:]))

print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [12]:
from pybrain3.datasets import SupervisedDataSet
from pybrain3.tools.shortcuts import buildNetwork
from pybrain3.supervised import BackpropTrainer

In [13]:
treinamento = SupervisedDataSet(4,1)

for i in range(len(entradas_treino)):
    treinamento.addSample(entradas_treino[i],saidas_treino[i])
    
print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [15]:
# construindo a rede

rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.5)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
#testando a rede
teste = SupervisedDataSet(4,1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i],saidas_teste[i])
    
trainer.testOnData(teste,verbose=True)


Testing on data:
out:     [  0.001]
correct: [  0.000]
error:  0.00000017
out:     [ -0.003]
correct: [  0.000]
error:  0.00000322
out:     [  0.006]
correct: [  0.000]
error:  0.00001836
out:     [  0.009]
correct: [  0.000]
error:  0.00004052
out:     [  0.002]
correct: [  0.000]
error:  0.00000309
out:     [  0.000]
correct: [  0.000]
error:  0.00000000
out:     [  0.038]
correct: [  0.000]
error:  0.00071069
out:     [  0.005]
correct: [  0.000]
error:  0.00001247
out:     [  0.014]
correct: [  0.000]
error:  0.00009667
out:     [  0.008]
correct: [  0.000]
error:  0.00002963
out:     [  0.012]
correct: [  0.000]
error:  0.00007311
out:     [ -0.001]
correct: [  0.000]
error:  0.00000034
out:     [  0.006]
correct: [  0.000]
error:  0.00001911
out:     [ -0.002]
correct: [  0.000]
error:  0.00000125
out:     [  0.003]
correct: [  0.000]
error:  0.00000346
out:     [  0.933]
correct: [  1.000]
error:  0.00225835
out:     [  0.973]
correct: [  1.000]
error:  0.00036697
out:     [  1

TypeError: list indices must be integers or slices, not float

In [17]:
# construindo a rede

rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# treinando a rede
for epoca in range(2000):
    trainer.train()
    
#testando a rede
teste = SupervisedDataSet(4,1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i],saidas_teste[i])
    
trainer.testOnData(teste,verbose=True)


Testing on data:
out:     [  0.028]
correct: [  0.000]
error:  0.00038829
out:     [  0.021]
correct: [  0.000]
error:  0.00023085
out:     [  0.034]
correct: [  0.000]
error:  0.00058549
out:     [  0.040]
correct: [  0.000]
error:  0.00079287
out:     [  0.030]
correct: [  0.000]
error:  0.00043846
out:     [  0.027]
correct: [  0.000]
error:  0.00037060
out:     [  0.083]
correct: [  0.000]
error:  0.00341516
out:     [  0.034]
correct: [  0.000]
error:  0.00056153
out:     [  0.053]
correct: [  0.000]
error:  0.00139179
out:     [  0.039]
correct: [  0.000]
error:  0.00075889
out:     [  0.047]
correct: [  0.000]
error:  0.00108733
out:     [  0.023]
correct: [  0.000]
error:  0.00026887
out:     [  0.035]
correct: [  0.000]
error:  0.00062583
out:     [  0.022]
correct: [  0.000]
error:  0.00024923
out:     [  0.030]
correct: [  0.000]
error:  0.00045679
out:     [  1.168]
correct: [  1.000]
error:  0.01407527
out:     [  1.232]
correct: [  1.000]
error:  0.02691321
out:     [  1

TypeError: list indices must be integers or slices, not float

In [18]:
# construindo a rede

rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.3, momentum=0.9)

# treinando a rede
for epoca in range(10000):
    trainer.train()
    
#testando a rede
teste = SupervisedDataSet(4,1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i],saidas_teste[i])
    
trainer.testOnData(teste,verbose=True)


Testing on data:
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  0.000]
error:  1.30979735
out:     [  1.619]
correct: [  1.000]
error:  0.19128115
out:     [  1.619]
correct: [  1.000]
error:  0.19128115
out:     [  1

TypeError: list indices must be integers or slices, not float

In [19]:
# Classificação com PyBrain = XOR de 3 dimensões

from pybrain3.datasets import SupervisedDataSet
from pybrain3.tools.shortcuts import buildNetwork
from pybrain3.supervised import BackpropTrainer

In [21]:
dataset = SupervisedDataSet(3,1)

In [22]:
dataset.addSample([0,0,0],[0])
dataset.addSample([0,0,1],[1])
dataset.addSample([0,1,0],[1])
dataset.addSample([0,1,1],[0])
dataset.addSample([1,0,0],[1])
dataset.addSample([1,0,1],[0])
dataset.addSample([1,1,0],[0])
dataset.addSample([1,1,1],[1])

In [24]:
network = buildNetwork(dataset.indim, 4, 4, dataset.outdim, bias=True)
trainer = BackpropTrainer(network, dataset, learningrate=0.01, momentum=0.9)

for i in range(1000):
    trainer.train()

test = SupervisedDataSet(3,1)
test.addSample([0,0,0],[0])
test.addSample([0,0,1],[1])
test.addSample([0,1,0],[1])
test.addSample([0,1,1],[0])
test.addSample([1,0,0],[1])
test.addSample([1,0,1],[0])
test.addSample([1,1,0],[0])
test.addSample([1,1,1],[1])

trainer.testOnData(test,verbose=True)


Testing on data:
out:     [  0.533]
correct: [  0.000]
error:  0.14224484
out:     [  0.520]
correct: [  1.000]
error:  0.11543201
out:     [  0.492]
correct: [  1.000]
error:  0.12895257
out:     [  0.446]
correct: [  0.000]
error:  0.09945501
out:     [  0.692]
correct: [  1.000]
error:  0.04739807
out:     [  0.506]
correct: [  0.000]
error:  0.12815839
out:     [  0.555]
correct: [  0.000]
error:  0.15420293
out:     [  0.479]
correct: [  1.000]
error:  0.13588586
All errors: [0.14224484362525885, 0.11543200899071165, 0.1289525722157202, 0.09945500638932368, 0.04739806842452102, 0.12815838931766477, 0.15420292714468126, 0.13588586309318754]
Average error: 0.11896620990013361


TypeError: list indices must be integers or slices, not float

In [25]:
network = buildNetwork(dataset.indim, 6, 6, dataset.outdim, bias=True)
trainer = BackpropTrainer(network, dataset, learningrate=0.01, momentum=0.9)

for i in range(1000):
    trainer.train()

test = SupervisedDataSet(3,1)
test.addSample([0,0,0],[0])
test.addSample([0,0,1],[1])
test.addSample([0,1,0],[1])
test.addSample([0,1,1],[0])
test.addSample([1,0,0],[1])
test.addSample([1,0,1],[0])
test.addSample([1,1,0],[0])
test.addSample([1,1,1],[1])

trainer.testOnData(test,verbose=True)


Testing on data:
out:     [ -0.007]
correct: [  0.000]
error:  0.00002342
out:     [  1.001]
correct: [  1.000]
error:  0.00000059
out:     [  0.991]
correct: [  1.000]
error:  0.00004355
out:     [  0.031]
correct: [  0.000]
error:  0.00047115
out:     [  1.031]
correct: [  1.000]
error:  0.00047180
out:     [ -0.004]
correct: [  0.000]
error:  0.00000922
out:     [  0.012]
correct: [  0.000]
error:  0.00006931
out:     [  0.984]
correct: [  1.000]
error:  0.00012692
All errors: [2.3415249619956187e-05, 5.921369044222373e-07, 4.355200544645497e-05, 0.00047114711306738965, 0.0004718022481655046, 9.215749530497551e-06, 6.931250507198143e-05, 0.0001269160676724377]
Average error: 0.00015199413443483053


TypeError: list indices must be integers or slices, not float

In [26]:
network = buildNetwork(dataset.indim, 6, 6, dataset.outdim, bias=True)
trainer = BackpropTrainer(network, dataset, learningrate=0.01, momentum=0.9)

for i in range(1500):
    trainer.train()

test = SupervisedDataSet(3,1)
test.addSample([0,0,0],[0])
test.addSample([0,0,1],[1])
test.addSample([0,1,0],[1])
test.addSample([0,1,1],[0])
test.addSample([1,0,0],[1])
test.addSample([1,0,1],[0])
test.addSample([1,1,0],[0])
test.addSample([1,1,1],[1])

trainer.testOnData(test,verbose=True)


Testing on data:
out:     [  0.030]
correct: [  0.000]
error:  0.00045462
out:     [  0.913]
correct: [  1.000]
error:  0.00374389
out:     [  0.913]
correct: [  1.000]
error:  0.00378813
out:     [  0.016]
correct: [  0.000]
error:  0.00013579
out:     [  0.922]
correct: [  1.000]
error:  0.00305976
out:     [  0.150]
correct: [  0.000]
error:  0.01125622
out:     [  0.093]
correct: [  0.000]
error:  0.00431367
out:     [  0.951]
correct: [  1.000]
error:  0.00119509
All errors: [0.0004546229893704399, 0.0037438899007367628, 0.0037881339530331007, 0.00013578587124511617, 0.0030597588949402075, 0.011256219611427394, 0.004313669719455859, 0.0011950859812482836]
Average error: 0.0034933958651821454


TypeError: list indices must be integers or slices, not float

In [32]:
network = buildNetwork(dataset.indim, 2, dataset.outdim, bias=True)
trainer = BackpropTrainer(network, dataset, learningrate=0.01, momentum=0.9)

for i in range(1500):
    trainer.train()

test = SupervisedDataSet(3,1)
test.addSample([0,0,0],[0])
test.addSample([0,0,1],[1])
test.addSample([0,1,0],[1])
test.addSample([0,1,1],[0])
test.addSample([1,0,0],[1])
test.addSample([1,0,1],[0])
test.addSample([1,1,0],[0])
test.addSample([1,1,1],[1])

trainer.testOnData(test,verbose=True)


Testing on data:
out:     [  0.451]
correct: [  0.000]
error:  0.10189097
out:     [  0.452]
correct: [  1.000]
error:  0.14990502
out:     [  0.447]
correct: [  1.000]
error:  0.15298902
out:     [  0.452]
correct: [  0.000]
error:  0.10197252
out:     [  0.456]
correct: [  1.000]
error:  0.14808166
out:     [  0.458]
correct: [  0.000]
error:  0.10481769
out:     [  0.451]
correct: [  0.000]
error:  0.10177648
out:     [  0.457]
correct: [  1.000]
error:  0.14744213
All errors: [0.10189096794704622, 0.1499050237527085, 0.15298901873742607, 0.1019725188043787, 0.1480816593835787, 0.10481769334621509, 0.10177648028431609, 0.14744212610429247]
Average error: 0.12610943604499525


TypeError: list indices must be integers or slices, not float