In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
np.insert(arr,1,10)

array([ 1, 10,  2,  3])

In [4]:
a = np.array([[1,2],[3,4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [6]:
print(a.sum(axis=0))
print(a.sum(axis=1))

[4 6]
[3 7]


In [7]:
np.insert(a,1,5,axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [8]:
np.insert(a,0,5,axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])

In [9]:
a = np.array([1,2,3])

In [10]:
np.append(a,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
np.append(a,[[5,6]])

array([1, 2, 3, 4, 5, 6])

In [13]:
np.append(a,[[5,6]],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.ndim

2

In [16]:
a2 = np.array([5,6,7])
a2.ndim

1

In [18]:
a = np.array([[1,2],[3,4],[5,6]])

In [19]:
np.delete(a,1,0)

array([[1, 2],
       [5, 6]])

In [20]:
np.delete(a,0,1)

array([[2],
       [4],
       [6]])

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.delete(a,np.s_[::2],0)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [23]:
a = np.array([[1,2],[3,4]])

In [24]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [25]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [26]:
np.repeat(a,2,0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [27]:
np.repeat(a,2,1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [28]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [29]:
a = np.array([1,2,3])

In [31]:
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [32]:
b = np.array([[1,2],[3,4]])

In [33]:
np.tile(b,2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [34]:
a = np.array([[1,2,3],[4,5,6]])

In [35]:
np.array_split(a,2,0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [36]:
np.array_split(a,2,1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [37]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [38]:
arrays = np.array_split(b,2,0)

for array in arrays:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [39]:
print(arrays)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [40]:
np.zeros(4)

array([0., 0., 0., 0.])

In [42]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [4]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
b.T

array([[5],
       [6]])

In [7]:
a.T

array([[1, 3],
       [2, 4]])

In [8]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])